version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGODB_DATABASE="employees"
    ports:
      - 27017:27017
    restart: always
    networks:
      - nesjs-network
  employee-service:
    build: .
    container_name: employee-api
    image: "employee-service:latest"
    ports:
      - 4200:3000
    depends_on:
      - mongodb
    networks:
      - nesjs-network
    restart: always
networks:
    nesjs-network:
      driver: bridge
